<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ts_register</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>72c366e1-81d8-40aa-aaa3-a071700b5a8a</testSuiteGuid>
   <testCaseLink>
      <guid>04ec74c8-6c8d-4179-a475-6fca13064d4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentification/tc_register_validation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8a8ca950-46d3-4e65-ad58-9f72e8dc0d5d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/RegisterData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8a8ca950-46d3-4e65-ad58-9f72e8dc0d5d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>7fde96c4-f91f-43fd-9166-dd2d32663835</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8a8ca950-46d3-4e65-ad58-9f72e8dc0d5d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>9f50534f-c90a-4aa6-bfaa-6f31552da3b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8a8ca950-46d3-4e65-ad58-9f72e8dc0d5d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedAlert</value>
         <variableId>ff306033-334c-42a9-a4c5-9d57b9ffa69c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
